# Generated by Django 4.0 on 2021-12-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_userslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersList',
        ),
    ]
