# Generated by Django 4.0 on 2021-12-15 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_delete_userslist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='candidates',
        ),
        migrations.AddField(
            model_name='post',
            name='candidates',
            field=models.CharField(default=[], max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='post',
            name='participants',
        ),
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
